import type { SignalDef } from "./types.js"

/**
 * Buying signals max can emit today, plus the watch-only signals from the
 * signal catalog so Grok can label evidence max has not productized yet.
 *
 * Strength order follows the outbound method: a tender outranks competitor
 * sales-team attention, which outranks a reposted role, which outranks a
 * fresh posting. A website visit is a hint. Fit alone is not a timing signal.
 */
export const SIGNALS: SignalDef[] = [
  {
    slug: "public-tenders",
    name: "Public tenders",
    family: "procurement",
    strength: 100,
    channelBias: "multichannel",
    liveNeedPrior: 0.95,
    available: true,
    summary: "A public body published a tender. The lead is the buyer, not a bidder.",
  },
  {
    slug: "public-contract-award",
    name: "Public contract awards",
    family: "procurement",
    strength: 92,
    channelBias: "multichannel",
    liveNeedPrior: 0.9,
    available: true,
    summary: "A newly won public contract creates immediate delivery work.",
  },
  {
    slug: "competitor-relationships",
    name: "Competitor sales relationships",
    family: "competitor",
    strength: 86,
    channelBias: "multichannel",
    liveNeedPrior: 0.75,
    available: true,
    summary: "A competitor's sales team just added this person. They are in a buying conversation.",
  },
  {
    slug: "mergers-acquisitions",
    name: "Mergers and acquisitions",
    family: "growth",
    strength: 80,
    channelBias: "multichannel",
    liveNeedPrior: 0.7,
    available: true,
    summary: "An M&A event. Systems, suppliers, and process are about to be reconsidered.",
  },
  {
    slug: "recruitment-campaign",
    name: "Hiring campaign",
    family: "hiring",
    strength: 78,
    channelBias: "multichannel",
    liveNeedPrior: 0.82,
    available: true,
    summary: "A spike in open roles. The team is in hypergrowth and the function is underbuilt.",
  },
  {
    slug: "republished-job-offers",
    name: "Reposted job openings",
    family: "hiring",
    strength: 74,
    channelBias: "multichannel",
    liveNeedPrior: 0.8,
    available: true,
    summary: "The same role went up again. The pain is persisting, not a one-week posting.",
  },
  {
    slug: "technology-replacement",
    name: "Technology replacement window",
    family: "technology",
    strength: 72,
    channelBias: "email",
    liveNeedPrior: 0.7,
    available: false,
    summary: "A tool disappeared or was replaced in the same category. Watch-only until max ships it.",
  },
  {
    slug: "key-departure",
    name: "Key departure",
    family: "people",
    strength: 70,
    channelBias: "linkedin",
    liveNeedPrior: 0.68,
    available: false,
    summary: "A departure opens an operational gap. Watch-only until max ships it.",
  },
  {
    slug: "regulatory",
    name: "Regulatory change",
    family: "market",
    strength: 66,
    channelBias: "email",
    liveNeedPrior: 0.6,
    available: false,
    summary: "New rules hit the sector and create compliance or operational work.",
  },
  {
    slug: "competitor-social-reactions",
    name: "Competitor GTM engagement",
    family: "competitor",
    strength: 64,
    channelBias: "linkedin",
    liveNeedPrior: 0.55,
    available: true,
    summary: "This person is engaging with a competitor's public posts.",
  },
  {
    slug: "fundraising",
    name: "Funding round",
    family: "growth",
    strength: 62,
    channelBias: "email",
    liveNeedPrior: 0.4,
    available: true,
    summary: "A verified raise. Cash is not a need unless the stated use matches the offer.",
  },
  {
    slug: "product-launch",
    name: "Product or service launch",
    family: "momentum",
    strength: 60,
    channelBias: "email",
    liveNeedPrior: 0.55,
    available: false,
    summary: "A new offer just went live and created positioning or delivery work.",
  },
  {
    slug: "job-offers",
    name: "New job posting",
    family: "hiring",
    strength: 58,
    channelBias: "email",
    liveNeedPrior: 0.62,
    available: true,
    summary: "A fresh role. Weaker than a repost: one posting can still be noise.",
  },
  {
    slug: "international-expansion",
    name: "International expansion",
    family: "momentum",
    strength: 58,
    channelBias: "email",
    liveNeedPrior: 0.55,
    available: false,
    summary: "The company is opening a new country and building the local operation.",
  },
  {
    slug: "job-changes",
    name: "Job change",
    family: "people",
    strength: 55,
    channelBias: "linkedin",
    liveNeedPrior: 0.5,
    available: true,
    summary: "A decision-maker in the first 90 days of a new mandate.",
  },
  {
    slug: "scaling-momentum",
    name: "Scaling momentum",
    family: "momentum",
    strength: 50,
    channelBias: "email",
    liveNeedPrior: 0.45,
    available: false,
    summary: "Hiring, headcount, tech, ads, and geography are moving together. A blend, not proof.",
  },
  {
    slug: "m-a-preparation",
    name: "M&A preparation",
    family: "growth",
    strength: 48,
    channelBias: "email",
    liveNeedPrior: 0.4,
    available: false,
    summary: "Several public changes look like a transaction being prepared. A forecast, not an announcement.",
  },
  {
    slug: "company-page-engagement",
    name: "Company page engagement",
    family: "engagement",
    strength: 48,
    channelBias: "linkedin",
    liveNeedPrior: 0.35,
    available: true,
    summary: "They engaged with a tracked company page. Interest, not a stated need.",
  },
  {
    slug: "influencer-engagement",
    name: "Influencer audience",
    family: "engagement",
    strength: 46,
    channelBias: "linkedin",
    liveNeedPrior: 0.32,
    available: true,
    summary: "They engaged with a category voice. They are learning, not buying yet.",
  },
  {
    slug: "partnership",
    name: "New partnership",
    family: "momentum",
    strength: 44,
    channelBias: "email",
    liveNeedPrior: 0.4,
    available: false,
    summary: "A partnership creates integration, channel, or delivery work.",
  },
  {
    slug: "linkedin-reactions",
    name: "Post reactions and comments",
    family: "engagement",
    strength: 44,
    channelBias: "linkedin",
    liveNeedPrior: 0.3,
    available: true,
    summary: "A reaction or comment on a specific post. Use the post as the hook, then stop if there is no need.",
  },
  {
    slug: "social-mentions",
    name: "Keyword and topic mentions",
    family: "engagement",
    strength: 42,
    channelBias: "linkedin",
    liveNeedPrior: 0.35,
    available: true,
    summary: "They discussed the pain, tool, or category in public.",
  },
  {
    slug: "major-website-change",
    name: "Major website change",
    family: "momentum",
    strength: 42,
    channelBias: "email",
    liveNeedPrior: 0.35,
    available: false,
    summary: "A launch, redesign, or migration. A hint of new work, not proof of budget.",
  },
  {
    slug: "likely-competitor-customers",
    name: "Likely competitor customers",
    family: "competitor",
    strength: 40,
    channelBias: "linkedin",
    liveNeedPrior: 0.35,
    available: false,
    summary: "Several traces suggest they use a competitor. No single mention is proof.",
  },
  {
    slug: "new-technology",
    name: "New technology detected",
    family: "technology",
    strength: 40,
    channelBias: "email",
    liveNeedPrior: 0.3,
    available: false,
    summary: "A relevant tool showed up in the stack. Context, not a deadline.",
  },
  {
    slug: "paid-media",
    name: "Paid media shift",
    family: "momentum",
    strength: 38,
    channelBias: "email",
    liveNeedPrior: 0.3,
    available: false,
    summary: "Visible advertising changed. A hint that growth spend is moving.",
  },
  {
    slug: "company-registration",
    name: "New company registration",
    family: "local",
    strength: 36,
    channelBias: "email",
    liveNeedPrior: 0.25,
    available: true,
    summary: "A newly registered company. Early, and often the wrong buyer.",
  },
  {
    slug: "ipo-readiness",
    name: "IPO readiness",
    family: "growth",
    strength: 36,
    channelBias: "email",
    liveNeedPrior: 0.3,
    available: false,
    summary: "Finance and governance changes look like public-market prep. A forecast.",
  },
  {
    slug: "linkedin-activity-resumes",
    name: "LinkedIn activity resumes",
    family: "engagement",
    strength: 34,
    channelBias: "linkedin",
    liveNeedPrior: 0.25,
    available: false,
    summary: "A quiet decision-maker started posting again. A hint to look, not to pitch.",
  },
  {
    slug: "google-business-listing",
    name: "New Google Maps listing",
    family: "local",
    strength: 30,
    channelBias: "email",
    liveNeedPrior: 0.2,
    available: true,
    summary: "A new local listing. Useful for local offers, weak everywhere else.",
  },
  {
    slug: "likely-fundraising",
    name: "Likely fundraising within 6 months",
    family: "growth",
    strength: 28,
    channelBias: "none",
    liveNeedPrior: 0.2,
    available: false,
    summary: "A blend that guesses a future raise. Not a need, and not cash in the bank.",
  },
  {
    slug: "radar-website",
    name: "Website visit",
    family: "hint",
    strength: 22,
    channelBias: "email",
    liveNeedPrior: 0.15,
    available: true,
    summary: "A website visit. A hint. Do not treat one visit as intent.",
  },
  {
    slug: "atlas-icp",
    name: "ICP match",
    family: "fit",
    strength: 18,
    channelBias: "none",
    liveNeedPrior: 0.05,
    available: true,
    summary: "They match the ICP and nothing else. Fit is not timing. Wait for a second signal.",
  },
]

const BY_SLUG = new Map(SIGNALS.map((signal) => [signal.slug, signal]))

export function getSignal(slug: string): SignalDef | undefined {
  return BY_SLUG.get(slug)
}

export function rankSignalSlugs(slugs: string[]): { primary: SignalDef | null; second: SignalDef | null } {
  const unique = [...new Set(slugs)]
  const defs = unique
    .map((slug) => getSignal(slug) ?? fallbackSignal(slug))
    .sort((a, b) => b.strength - a.strength)
  return { primary: defs[0] ?? null, second: defs[1] ?? null }
}

function fallbackSignal(slug: string): SignalDef {
  return {
    slug,
    name: slug,
    family: "unlisted",
    strength: 40,
    channelBias: "email",
    liveNeedPrior: 0.3,
    available: false,
    summary: "Signal slug was not in the catalog. Grok should read the evidence before trusting it.",
  }
}
